spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:issue-tracker;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 10
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
      encoding: UTF-8

logging:
  level:
    root: info
    org.hibernate.SQL: debug
